const FETCH_ALL_BOOKS = "FETCH_ALL_BOOKS";
const CREATE_BOOK = "CREATE_BOOK";
const EDIT_BOOK = "EDIT_BOOK";
const DELETE_BOOK = "DELETE_BOOK";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

export {
    FETCH_ALL_BOOKS,
    CREATE_BOOK,
    EDIT_BOOK,
    DELETE_BOOK,
    AUTHENTICATION,
    LOGOUT
}